.PHONY: clean All

All:
	@echo "----------Building project:[ tach-mang - Debug ]----------"
	@cd "tach-mang" && "$(MAKE)" -f  "tach-mang.mk"
clean:
	@echo "----------Cleaning project:[ tach-mang - Debug ]----------"
	@cd "tach-mang" && "$(MAKE)" -f  "tach-mang.mk" clean
