.PHONY: clean All

All:
	@echo "----------Building project:[ daochuoi - Debug ]----------"
	@cd "daochuoi" && "$(MAKE)" -f  "daochuoi.mk"
clean:
	@echo "----------Cleaning project:[ daochuoi - Debug ]----------"
	@cd "daochuoi" && "$(MAKE)" -f  "daochuoi.mk" clean
