.PHONY: clean All

All:
	@echo "----------Building project:[ sotietkiem - Debug ]----------"
	@cd "sotietkiem" && "$(MAKE)" -f  "sotietkiem.mk"
clean:
	@echo "----------Cleaning project:[ sotietkiem - Debug ]----------"
	@cd "sotietkiem" && "$(MAKE)" -f  "sotietkiem.mk" clean
