.PHONY: clean All

All:
	@echo "----------Building project:[ BAI1 - Debug ]----------"
	@cd "BAI1" && "$(MAKE)" -f  "BAI1.mk"
clean:
	@echo "----------Cleaning project:[ BAI1 - Debug ]----------"
	@cd "BAI1" && "$(MAKE)" -f  "BAI1.mk" clean
