.PHONY: clean All

All:
	@echo "----------Building project:[ DifferentBits - Debug ]----------"
	@cd "DifferentBits" && "$(MAKE)" -f  "DifferentBits.mk"
clean:
	@echo "----------Cleaning project:[ DifferentBits - Debug ]----------"
	@cd "DifferentBits" && "$(MAKE)" -f  "DifferentBits.mk" clean
